services:
  db:
    image: postgres:15
    container_name: whiteboard_postgres
    restart: always
    environment:
      POSTGRES_USER: whiteboarduser
      POSTGRES_PASSWORD: whiteboardpass
      POSTGRES_DB: whiteboard_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: